### PR TITLE
Added "Report" option to memo right-click menu, + misc QoL changes

### PR DESCRIPTION
**Pull request by maloryware**
Title + Removed "(optional)" from the report window to discourage empty reports.

### CODE REVIEW

**Comment by Dpeta** [comment]
hm,,,
image

**Comment by maloryware** [comment]
Guh. Fixing

**Comment by maloryware** [comment]
Report content fixed, added obligatory status to "reason" field

**Comment by maloryware** [comment]
With this, both REPORT on memos and the update popup are complete. In the future it may be worth changing the sizepolicy for the lefthandLayout to make it less painful and unbearable to resize the window in order to read the changelog. It's not a criminally awful thing, but definitely reasonable QoL to consider

**Comment by maloryware** [comment]
never let me say "this PR is now complete" ever again

**Comment by mocchapi** [comment]
image

**Comment by Dpeta** [comment]
that commit history is so real

**Pull request merged**
