### PR TITLE
Reformat codebase

### PR DESCRIPTION
**Pull request by MiguelX413**
With this pull request, I intend to:
1. Reformat the codebase with black
2. Add a github action enforcing black
3. Add a github action for building pesterchum
4. Maybe add type annotations, or at least mypy compliance

### CODE REVIEW

**Comment by MiguelX413** [comment]
I'd also like to discuss the possibility of replacing the dashes in the github project with underscores, as is preferred in Python.

**Comment by MiguelX413** [comment]
> The code is definitely very inconsistent when it comes to style, reformatting it with black seems like a good idea to me.
> 
> Do you mean an action for building it as a traditional package or as an executable with pyinstaller? :?

I mean the latter, though both could be done

> As far as I'm aware dashes only break pep 8 convention when it comes to module/package names, and the name of the repository doesn't necessarily also have to be the name of the resulting package/module. When testing building as a wheel I just used "pesterchum_alt", though mybe just "pesterchum" would suffice too.
> 
> I've thought about renaming the repository to something else (possibly just 'pesterchum') but I feel like that might be a bit of a messy transition, so I'd prefer not to unless there's a compelling reason.

Github automatically creates redirects when a repo is renamed, like with https://github.com/MiguelX413/intevalla

@Dpeta

**Review by Dpeta — APPROVED** [review]
Seems like running it through black didn't break anything. It might be easier to just merge this rn and make separate pull requests for further changes, as reformatting to this extent will definitely cause merge conflicts with further commits.

**Comment by MiguelX413** [comment]
> Seems like running it through black didn't break anything. It might be easier to just merge this rn and make separate pull requests for further changes, as reformatting to this extent will definitely cause merge conflicts with further commits.

Sounds good
How about this + a GitHub action for black?

**Comment by Dpeta** [comment]
Alright nice, thanks 🐈🎉 ~~(seems like the force-push overwrote my edit but I'll just commit that again later)~~

**Comment by MiguelX413** [comment]
> Alright nice, thanks cat2tada ~(seems like the force-push overwrote my edit but I'll just commit that again later)~

Sorry! I didn't notice!

**Pull request merged**
